-- Chạy script này trong SQL Editor của Supabase
-- Chọn schema mặc định là public hoặc oltp_store nếu có dropdown

SET search_path TO oltp_store;

-- 1. Sửa lỗi ID của bảng categories không tự động tăng
-- Nếu column 'id' chưa có IDENTITY, lệnh này sẽ thêm tính năng tự động tăng.
-- Chúng ta dùng khối DO để kiểm tra và an toàn thêm IDENTITY.

DO $$
DECLARE
    is_identity text;
BEGIN
    SELECT is_identity INTO is_identity 
    FROM information_schema.columns 
    WHERE table_schema = 'oltp_store' 
      AND table_name = 'categories' 
      AND column_name = 'id';

    IF is_identity = 'NO' THEN
        -- Bỏ default hiện tại (nếu có nhưng bị hỏng)
        ALTER TABLE oltp_store.categories ALTER COLUMN id DROP DEFAULT;
        -- Thêm lại IDENTITY để tự động tăng
        ALTER TABLE oltp_store.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        
        -- Cập nhật lại giá trị sequence để tránh trùng lặp
        PERFORM setval(pg_get_serial_sequence('oltp_store.categories', 'id'), coalesce(max(id), 0) + 1, false) FROM oltp_store.categories;
    END IF;
END $$;

-- 2. Thêm PostgREST Foreign Key comments cho view camera_models
-- Giúp Supabase Client có thể join bảng (không bắt buộc vì backend đã được viết lại, nhưng tốt cho tương lai)
COMMENT ON VIEW oltp_store.camera_models IS E'@foreignKey (catgories_id) references categories (id)';

